MAINT Remove gcc conda install
civisanalytics/datascience-python pull request #27
Opened 2017-03-20 14:14 UTC by stephen-hoover

The gcc package we specified is not present in the OS X channels, so it blocked installation of this environment file in OS X. It's not necessary for any of the package installations, so remove it.

2017-03-20 14:57 UTC, stephen-hoover commented
@beckermr , do you know if there was a good reason to include `libgcc` in the conda environment file?

2017-03-20 15:09 UTC, beckermr commented
Yeah....

1. This env does not build on OS X for more than just this reason. This problem is in part why I created the XGBoost package on conda-forge, since the pip install for that on mac for version 0.6a2 is broken unless you have some deps from brew.
2. I have no idea how `libgcc` got in there. This package was added in your initial commit. :)

<img width="1293" alt="screen shot 2017-03-20 at 10 06 40 am" src="https://cloud.githubusercontent.com/assets/5296416/24106139/fe9b6da8-0d54-11e7-84f8-55a66ae904d3.png">

2017-03-20 15:14 UTC, beckermr requested changes
Just a few comments. I don't think this PR will fix all mac OS X problems.

2017-03-20 15:14 UTC, beckermr commented on CHANGELOG.md
> +- Remove conda install of gcc. This prevented use of the environment file in OS X, and isn't necessary for any other packages.
This should be more specific. `conda` has separate packages for `gcc` and `libgcc`. Usually, `gcc` is used to build stuff and then you just specify `libgcc` as a run-time dependence. See my [recipe](https://github.com/conda-forge/staged-recipes/pull/2628) for XGBoost, for example.

2017-03-20 15:14 UTC, beckermr commented on environment.yml
> -- libgcc=5.2.0
FWIW, `libgcc` 4.8.5 is available on OS X from defaults, not that this matters. If we do not need `libgcc` as a runtime dependence, then we should get rid of it.

2017-03-20 16:01 UTC, stephen-hoover commented
@beckermr , it did build on my machine, so I must have the required version of gcc from brew. I found that I was pulling `libsodium` from conda-forge, though. That's the same situation as `libgcc` -- it's a dependency which conda pulls automatically in linux, but which isn't needed / available in OS X.

2017-03-20 16:21 UTC, beckermr commented
Right ok. So right now, even with these changes, this env will not necessarily build on OS X. Should we add docs to this effect, let people figure it out, or just say nothing?

2017-03-20 16:23 UTC, stephen-hoover commented
I'll put something in the README. Do you have the error message handy for when people don't have the proper gcc installed? And is the solution `brew install gcc`?

2017-03-20 16:42 UTC, beckermr commented
Honestly, the better solution is to install gcc 4.8.5 and libgcc 4.8.5 from conda.

2017-03-20 16:50 UTC, stephen-hoover commented
Why? How does that help?

2017-03-20 16:53 UTC, beckermr commented
I changed my comments. You can get all deps from conda, but you have to edit the xgboost makefile to get it to compile. This is in the conda-forge package I made for xgboost.

2017-03-20 17:01 UTC, beckermr commented
The conda-forge package with OpenMP on OS X is here:

https://github.com/conda-forge/staged-recipes/pull/2628

Hopefully it will get merged soon. Then we can just direct people there.

2017-03-21 22:43 UTC, stephen-hoover commented
@beckermr , I added a section to the README. I think I've addressed your comments now.

2017-03-21 22:47 UTC, beckermr approved these changes
LGTM

2017-03-21 22:47 UTC, beckermr commented on README.md
> +the `gcc` v5 or the `clang-omp` compiler, neither of which are natively provided in OS X.
LGTM

2017-03-21 22:47 UTC, beckermr commented on README.md
> +`brew install gcc@5 --without-multilib`. Be warned that this installation will take
we could warn about linking, paths, etc but I think this is good.

2017-03-21 22:49 UTC, merged