BUG Use /tmp for joblib temp files instead of /shm
civisanalytics/datascience-python pull request #37
Opened 2017-06-19 14:41 UTC by stephen-hoover

Instruct joblib to use disk for temporary files. Joblib defaults to /shm when that directory is present. In the Docker container, /shm is present but defaults to 64 MB. That's not enough space to handle even moderate-sized computations. The temporary directory is a bit slower, but has much more space.

 https://github.com/joblib/joblib/blob/0.11/joblib/parallel.py#L328L342

2017-06-19 15:57 UTC, beckermr requested changes

2017-06-19 15:57 UTC, beckermr commented on Dockerfile
> +ENV JOBLIB_TEMP_FOLDER=/tmp
My inclination is to not accept this PR. This seems like an option that should be set by users at runtime or somewhere else in downstream process, not in a general, base container for doing things.

2017-06-19 19:21 UTC, stephen-hoover commented on Dockerfile
> +ENV JOBLIB_TEMP_FOLDER=/tmp
The reason I think it's worthwhile having here is that this image is the execution environment for Python scripts in the Civis Platform, and is also the default image for container scripts. Without instructing joblib to use /tmp, joblib will fail in an unintuitive way. This means that users will get confusing errors if they try to set `n_jobs` to anything other than 1 in most of scikit-learn, for example.

This only affects joblib memmapping, and without this, joblib memmapping will almost always fail.

2017-06-19 20:03 UTC, beckermr commented on Dockerfile
> +ENV JOBLIB_TEMP_FOLDER=/tmp
Fair enough. Let's put a big old warning somewhere and move on.

2017-06-19 20:03 UTC, beckermr commented
@stephen-hoover Let's add a warning to the readme and then merge this.

2017-06-19 22:07 UTC, stephen-hoover commented
@beckermr , I added a sub-section to the README about this.

2017-06-20 14:31 UTC, beckermr approved these changes

2017-06-20 14:31 UTC, beckermr commented
LGTM

2017-06-20 14:40 UTC, merged