[CIVP-12592] Update requests to 2.18.4
civisanalytics/datascience-python pull request #42
Opened 2017-09-08 02:06 UTC by jacksonllee

This PR updates the version of `requests` to the most up-to-date 2.18.4, so that we can take advantage of some of the recently added features, e.g. the `with` context manager syntax of a `requests` response.

2017-09-08 03:34 UTC, jacksonllee commented on circle.yml
> +        - docker run civisanalytics/datascience-python /bin/bash -c "conda list|grep conda-forge"
For our purposes, it seems a little tricky to tell which packages (and for which exact versions) have just been added to conda-forge in order to make sure the conda-forge package count assertion test will pass at any given point of time. So I've added this line just to show what the build thinks the conda-forge packages are -- useful when the assertion test fails and we have to change the expected package count just one line below.

2017-09-08 14:34 UTC, jacksonllee commented
Just merged in the master branch and fixed the conflict. Ready for a pass! @stephen-hoover

2017-09-08 15:05 UTC, jacksonllee commented
@stephen-hoover Based on discussion on JIRA, I've switched to pip install for updating `requests`, in order to not mess with the control for conda-forge usage. Ready for a pass!

2017-09-08 16:33 UTC, stephen-hoover requested changes
When I check the container build logs in the tests, I see two potential issues. First is that conda installs requests 2.12.4 during the build process, probably because it's a dependency of another conda-installed package. I suspect this means that we end up with two versions of {{requests}}  in the conda environment, because pip can't uninstall conda packages. You could check this by building the container locally and doing a `docker run conda list`.

Second, I see the following warning:
```
/opt/conda/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.19) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```
Does this mean that we also need a newer version of `urllib3`?

2017-09-08 17:01 UTC, jacksonllee commented
For the warning regarding `urllib3`, I've updated its version as well and the `RequestsDependencyWarning` doesn't show up anymore.

For the `requests` version, the container build log says that conda is installing 2.12.4 at first, but afterwards 2.18.4 is downloaded and installed, and 2.12.4 is uninstalled.

2017-09-09 01:11 UTC, jacksonllee commented
aaaaaaand we're now back to conda-forge for `requests`, based on offline discussion with @stephen-hoover. I've also built the container locally and verified that there is only one single `requests` installed:

```
...
readline                  6.2                           2    defaults
requests                  2.18.4                   py36_1    conda-forge
requests-toolbelt         0.8.0                     <pip>
...
```

Ready for review!

2017-09-09 01:13 UTC, jacksonllee commented on circle.yml
> +        - docker run civisanalytics/datascience-python /bin/bash -c "conda list|grep conda-forge"
It's also useful even if the assertion test passes. We know exactly what the conda-forge packages are:

```
arrow-cpp                 0.5.0               np113py36_2    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
jemalloc                  4.4.0                         0    conda-forge
parquet-cpp               1.2.0                         0    conda-forge
pyarrow                   0.5.0               np113py36_0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
xgboost                   0.6a2                    py36_2    conda-forge
```

2017-09-11 14:00 UTC, stephen-hoover approved these changes
LGTM! Thank you for pushing through the back-and-forth.

2017-09-11 14:05 UTC, merged