[CIVIS-6103] fix missing public keys
civisanalytics/datascience-python pull request #91
Opened 2023-07-28 15:06 UTC by videogaber

2023-07-28 18:23 UTC, fahaddd-git commented on buildspec/push.yaml
> +      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
aws ecr get-login-password --region ${AWS_DEFAULT_REGION}| docker login --username AWS --password-stdin ${REPOSITORY_URI}

2023-07-31 16:05 UTC, mwpeterson requested changes
minor cleanup

2023-07-31 16:05 UTC, mwpeterson commented on buildspec/release.yaml
> +      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
This is better in the `pre-build` phase.

2023-07-31 16:05 UTC, mwpeterson commented on buildspec/release.yaml
> +      - docker push ${REPOSITORY_URI}:${MAJOR_TAG}
Now that this is on the new codebuild image with docker 20.10 you can do
```suggestion
      - docker image push --all-tags  ${REPOSITORY_URI}
```

2023-07-31 16:55 UTC, videogaber commented on buildspec/release.yaml
> +      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
i had it in the pre-build stage before. when it came to trying to push the image, the login didnt seem to take and failed

2023-07-31 16:56 UTC, videogaber commented on buildspec/release.yaml
> +      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
so i had everything be part of the same set of commands. and that did the trick

2023-07-31 17:47 UTC, mwpeterson approved these changes
lgtm

2023-07-31 17:47 UTC, mwpeterson commented on buildspec/release.yaml
> +      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
Strange.

2023-07-31 18:02 UTC, merged